version: '3.1'
services:
  app:
    container_name: machinery-type-ms
    image: durpyshark/machinery-type-ms
    build: ./
    ports:
      - "8083:8083"
    depends_on:
      - machinery_types_db_container
  machinery_types_db_container:
    image: postgres
    ports:
      - "5435:5435"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=machinery_types_db
    command: -p 5435